name: Publish

on:
  push:
    tags:
      - "*"

env:
  PROJECT_ID: "521527"

jobs:
  modpack-info:
    runs-on: ubuntu-latest
    outputs:
      projectname: ${{ steps.info.outputs.projectname }}
      version: ${{ steps.info.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get modpack info
        id: info
        run: |
            manifestjson=`cat ./modpack/manifest.json`
            projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
            echo "::set-output name=projectname::$projectname"
            version=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
            echo "::set-output name=version::$version"
      - name: Get tag
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

  changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        run: |
            cat > CHANGELOG.md << EOF
            $(./.github/scripts/generate-changelog.sh)
            EOF
      - name: Store changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  build:
    runs-on: ubuntu-latest
    needs: [changelog, modpack-info]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download PAX
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: froehlichA/pax
          file: "pax"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Move changelog
        run:  mv ./CHANGELOG.md ./modpack/CHANGELOG.md
      - name: Export modpack
        run: |
          sudo chmod +x ./pax
          ./pax export
      - name: Build serverpack
        uses: Multiplayer-co-at/cursforge-modpack-generator@main
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          clientpack: .out/${{ needs.modpack-info.outputs.projectname }}.zip
      - name: Rename zip
        run: |
          mv .out/${{ needs.modpack-info.outputs.projectname }}.zip .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.version }}-${{ needs.modpack-info.outputs.tag }}.zip
          mv .out/serverpack.zip .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.version }}-${{ needs.modpack-info.outputs.tag }}-server.zip
      - name: Upload client zip
        uses: actions/upload-artifact@v2
        with:
          name: clientpack
          path: .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.version }}-${{ needs.modpack-info.outputs.tag }}.zip
      - name: Upload server zip
        uses: actions/upload-artifact@v2
        with:
          name: serverpack
          path: .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.version }}-${{ needs.modpack-info.outputs.tag }}-server.zip

  release-github:
    runs-on: ubuntu-latest
    needs: [build, changelog, modpack-info]
    steps:
      - name: Download client zip
        uses: actions/download-artifact@v2
        with:
          name: clientpack
      - name: Download server zip
        uses: actions/download-artifact@v2
        with:
          name: serverpack
      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-curseforge:
    runs-on: ubuntu-latest
    needs: [build, changelog, modpack-info]
    steps:
      - name: Download client zip
        uses: actions/download-artifact@v2
        with:
          name: clientpack
      - name: Download server zip
        uses: actions/download-artifact@v2
        with:
          name: serverpack
      - name: Get release type
        id: release-type
        run: |
          rel_type="release"
          case "${{ needs.modpack-info.outputs.tag }}" in
            *alpha*) rel_type="alpha" ;;
            *beta*) rel_type="beta" ;;
            *) rel_type="release" ;;
          esac
          echo "::set-output name=type::$rel_type"
      - name: Create release
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}
          project_id: '521527'
          modpack-path: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.version }}-${{ needs.modpack-info.outputs.tag }}.zip
          modpack-server-path: ${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.version }}-${{ needs.modpack-info.outputs.tag }}-server.zip
          changelog: "${{ needs.changelog.outputs.changelog }}"
          changelog-format: 'markdown'
          game-versions: "${{ needs.modpack-info.outputs.version }}"
          release_type: ${{ steps.release-type.outputs.type }}
